datasources:
- name: Prometheus
  access: proxy
  type: prometheus
  url: http://prometheus:9090
  isDefault: true
- name: Alertmanager
  type: alertmanager
  url: http://alertmanager:9093
  access: proxy
  jsonData:
    implementation: prometheus
    handleGrafanaManagedAlerts: true